# Generated by Django 5.2.9 on 2026-02-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_booking_last_name_alter_booking_reservation_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
